export const BRAND = {
  AUTHOR: "Rijal Ghodi",
  AUTHOR_URL: "https://github.com/rijalghodi",
  EMAIL: "rijalghodi.dev@gmail.com",
  SITE_NAME: "Memr, AI-powered second brain",
  APP_NAME: "Memr",
  APP_TAGLINE: "AI-powered second brain",
  OG_IMAGE_URL: `https://memr-ai.vercel.app/opengraph-image.png`,
  SITE_DESCRIPTION:
    "Memr is an AI-powered knowledge management application that helps you organize your thoughts, tasks, and resources in a single, intelligent workspace.",
  KEYWORDS: [
    "Memr",
    "Memories",
    "Thoughts",
    "Notes",
    "Journals",
    "AI",
    "Second Brain",
    "Productivity",
    "Task Management",
    "Note-taking",
    "Project Management",
    "Task Management",
    "Note-taking",
    "Project Management",
  ],
};
