basePath: /v1
definitions:
  contract.Change:
    properties:
      collectionId:
        description: Note-only
        type: string
      color:
        description: Project and collection-only
        type: string
      content:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      description:
        type: string
      dueDate:
        type: string
      id:
        type: string
      projectId:
        description: Task-only
        type: string
      sortOrder:
        type: string
      status:
        type: integer
      title:
        type: string
      type:
        description: '"task" or "project" or "note" or "collection"'
        type: string
      updatedAt:
        type: string
    required:
      - id
    type: object
  contract.GoogleOAuthReq:
    properties:
      idToken:
        type: string
    required:
      - idToken
    type: object
  contract.GoogleOAuthRes:
    properties:
      accessToken:
        type: string
      accessTokenExpiresAt:
        type: string
      createdAt:
        type: string
      email:
        type: string
      id:
        type: string
      isVerified:
        type: boolean
      name:
        type: string
      refreshToken:
        type: string
      refreshTokenExpiresAt:
        type: string
      updatedAt:
        type: string
    type: object
  contract.RefreshTokenReq:
    properties:
      refreshToken:
        type: string
    required:
      - refreshToken
    type: object
  contract.RefreshTokenRes:
    properties:
      accessToken:
        type: string
      accessTokenExpiresAt:
        type: string
      createdAt:
        type: string
      email:
        type: string
      id:
        type: string
      isVerified:
        type: boolean
      name:
        type: string
      refreshToken:
        type: string
      refreshTokenExpiresAt:
        type: string
      updatedAt:
        type: string
    type: object
  contract.SyncReq:
    properties:
      changes:
        items:
          $ref: "#/definitions/contract.Change"
        type: array
      lastSyncTime:
        type: string
    type: object
  contract.SyncRes:
    properties:
      changes:
        items:
          $ref: "#/definitions/contract.Change"
        type: array
      lastSyncTime:
        type: string
    type: object
  contract.UserRes:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: string
      isVerified:
        type: boolean
      name:
        type: string
      updatedAt:
        type: string
    type: object
  util.BaseResponse:
    properties:
      data: {}
      details: {}
      message:
        type: string
      status:
        type: boolean
    type: object
host: localhost:3000
info:
  contact:
    email: rijalghodi.dev@gmail.com
    name: Rijal Ghodi
  description: Second brain that understand you. Manage project, todo, and resources
    in single app.
  license:
    name: MIT
  title: Memr API
  version: 1.0.0
paths:
  /v1/auth/google:
    post:
      consumes:
        - application/json
      description: Google OAuth authentication
      parameters:
        - description: Google OAuth request
          in: body
          name: request
          required: true
          schema:
            $ref: "#/definitions/contract.GoogleOAuthReq"
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: "#/definitions/util.BaseResponse"
              - properties:
                  data:
                    $ref: "#/definitions/contract.GoogleOAuthRes"
                type: object
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/util.BaseResponse"
      summary: Google OAuth
      tags:
        - Auth
  /v1/auth/me:
    get:
      consumes:
        - application/json
      description: Get current user information
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: "#/definitions/util.BaseResponse"
              - properties:
                  data:
                    $ref: "#/definitions/contract.UserRes"
                type: object
        "401":
          description: Unauthorized
          schema:
            $ref: "#/definitions/util.BaseResponse"
      summary: Get current user
      tags:
        - Auth
  /v1/auth/refresh-token:
    post:
      consumes:
        - application/json
      description: Refresh access token using refresh token
      parameters:
        - description: Refresh token request
          in: body
          name: request
          required: true
          schema:
            $ref: "#/definitions/contract.RefreshTokenReq"
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: "#/definitions/util.BaseResponse"
              - properties:
                  data:
                    $ref: "#/definitions/contract.RefreshTokenRes"
                type: object
        "401":
          description: Unauthorized
          schema:
            $ref: "#/definitions/util.BaseResponse"
      summary: Refresh token
      tags:
        - Auth
  /v1/sync:
    post:
      consumes:
        - application/json
      description: Sync data between client and server
      parameters:
        - description: Sync request
          in: body
          name: request
          required: true
          schema:
            $ref: "#/definitions/contract.SyncReq"
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: "#/definitions/util.BaseResponse"
              - properties:
                  data:
                    $ref: "#/definitions/contract.SyncRes"
                type: object
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/util.BaseResponse"
        "401":
          description: Unauthorized
          schema:
            $ref: "#/definitions/util.BaseResponse"
      security:
        - BearerAuth: []
      summary: Sync data
      tags:
        - Sync
securityDefinitions:
  BearerAuth:
    description: "Example Value: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
